version: '3'
services:
  backend:
    depends_on:
      - database
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: vitor96k/node-challenge
    ports:
      - 3000:3000
    volumes:
      - './backend:/app'
    tty: true

  database:
    restart: always
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - environment_variables.env
