version: '3'
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: vitor96k/node-challenge
    ports:
      - 3000:3000
    volumes:
      - './backend:/app'
      - /app/node_modules
    tty: true


