version: '3'
services:
  backend:
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: vitor96k/node-challenge
    ports:
      - 3000:3000
    volumes:
      - './backend:/app'
    tty: true
    env_file:
      - environment_variables.env
    command: ash -c "dockerize -wait tcp://database:3306 -timeout 60s && npm run start:dev"

  database:
    restart: always
    image: mysql:8.0.30
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - environment_variables.env
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
      - type: bind
        source: ./mysql
        target: /docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db: